# Generated by Django 5.2.8 on 2025-11-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guests_count",
                    models.PositiveIntegerField(
                        help_text="Выберите количество гостей",
                        verbose_name="Количество гостей",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="Укажите время начала бронирования",
                        verbose_name="Время начала бронирования",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Выберите продолжительность брони",
                        verbose_name="Продолжительность брони",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Укажите комментарий (при необходимости)",
                        max_length=300,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "бронь",
                "verbose_name_plural": "брони",
                "ordering": ["guests_count", "start_time", "table", "user"],
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Укажите номер стола",
                        unique=True,
                        verbose_name="Номер стола",
                    ),
                ),
                (
                    "guests_count",
                    models.PositiveIntegerField(
                        help_text="Укажите количество гостей",
                        verbose_name="Количество гостей",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="Выберите тип стола (при необходимости)",
                        max_length=100,
                        null=True,
                        verbose_name="Тип стола",
                    ),
                ),
            ],
            options={
                "verbose_name": "стол",
                "verbose_name_plural": "столы",
                "ordering": ["guests_count", "type", "number"],
            },
        ),
    ]
