# Generated by Django 5.2.8 on 2025-11-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["start_time", "guests_count", "table", "user"],
                "verbose_name": "бронь",
                "verbose_name_plural": "брони",
            },
        ),
        migrations.AlterField(
            model_name="reservation",
            name="comment",
            field=models.TextField(
                blank=True, max_length=300, null=True, verbose_name="Комментарий"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="duration",
            field=models.PositiveIntegerField(verbose_name="Продолжительность брони"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="guests_count",
            field=models.PositiveIntegerField(verbose_name="Количество гостей"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="start_time",
            field=models.DateTimeField(verbose_name="Время начала бронирования"),
        ),
    ]
