# Generated by Django 5.2.8 on 2025-11-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurant",
            "0003_alter_reservation_options_alter_reservation_comment_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="type",
            field=models.CharField(
                blank=True,
                help_text="Укажите тип стола (при необходимости)",
                max_length=100,
                null=True,
                verbose_name="Тип стола",
            ),
        ),
    ]
