# Generated by Django 5.2.8 on 2025-11-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_alter_table_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Бронь активна"),
        ),
    ]
