# Generated by Django 5.2.8 on 2025-11-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Уникальная метка",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug (метка)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="assets/img",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Подзаголовок",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Текст"
                    ),
                ),
            ],
            options={
                "verbose_name": "блок контента",
                "verbose_name_plural": "блоки контента",
            },
        ),
    ]
