# Generated by Django 5.2.8 on 2025-11-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentblock",
            name="body",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="Текст"
            ),
        ),
    ]
