# Generated by Django 5.2.8 on 2025-11-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_contentblock_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentblock",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="img", verbose_name="Фото"
            ),
        ),
    ]
